### ISSUE TITLE
The store does not open by right-clicking

### ISSUE THREAD

**Issue by ghost** [moomaxie/BetterShops#10]
The store does not open by right-clicking on the name plate on the chest. Result: nothing happens. No errors in the console. Powered by a chief administrator.

BetterShop 2.0.9
KCauldron 1.7.10

**Comment by moomaxie** [comment]
Cauldron does not support the NPC option for this plugin. I have tried again and again to fix this but there is no point, especially if Cauldron will no longer be updating.

**Comment by ghost** [comment]
KCauldron updated and providing support. And KCauldron uses a lot of servers.

https://gitlab.prok.pw/Prototik/KCauldron

**Comment by sameer** [comment]
@moomaxie Sorry to revive this issue, but I am currently maintaining the TCPR Unofficial KCauldron [here](https://github.com/TCPR/KCauldron). I would like to integrate support for the BetterShops plugin on KCauldron. Please let me know if you are interested. Thanks.

**Comment by SrAnthony** [comment]
@Robotia I'm searching for a good shop plugin for days, and I will really appreciate if you integrate this one. 
PS: I am using your KCauldron version ;)

**Comment by sameer** [comment]
@Esctogrillo Please see https://github.com/Robotia/BetterShops/releases
