### ISSUE TITLE
False declaration

### ISSUE THREAD

**Issue by BellemareMederic** [moomaxie/BetterShops#17]
i creat sign shop whit Diamond_axe and error occur on /reload... 

No enum constant org.bukkit.Material._DIAMOND_AXE

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (source of bukkit obj name)

why obj name is "_DIAMOND_AXE"
but the real name is "DIAMOND_AXE"

20:58:57 CONSOLE: [INFO] BetterShops - An error occurred! Please inform the developer @ http://dev.bukkit.org/bukkit-plugins/better-shops/ . Plugin Disabling!
20:58:57 CONSOLE: WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material._DIAMOND_AXE
20:58:57 CONSOLE: WARN]: at java.lang.Enum.valueOf(Unknown Source)
20:58:57 CONSOLE: WARN]: at org.bukkit.Material.valueOf(Material.java:1)
20:58:57 CONSOLE: WARN]: at max.hubbard.bettershops.Shops.Types.Sign.SignShopManager.loadSignShops(SignShopManager.java:182)
20:58:57 CONSOLE: WARN]: at max.hubbard.bettershops.Core.loadShops(Core.java:456)
20:58:57 CONSOLE: WARN]: at max.hubbard.bettershops.Core.onEnable(Core.java:229)
20:58:57 CONSOLE: WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
20:58:57 CONSOLE: WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
20:58:57 CONSOLE: WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
20:58:57 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
20:58:58 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
20:58:58 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
20:58:58 CONSOLE: WARN]: at org.bukkit.Bukkit.reload(Bukkit.java:535)
20:58:58 CONSOLE: WARN]: at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
20:58:58 CONSOLE: WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
20:58:58 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
20:58:58 CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
20:58:58 CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
20:58:58 CONSOLE: WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
20:58:58 CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by sameer** [comment]
@jak645 just fixed it.

**Comment by BellemareMederic** [comment]
Thx

**Comment by ghost** [comment]
yea, but now we need a new build? anyone able to get a response from moomaxie?

**Comment by sameer** [comment]
@jak645 Please see https://github.com/Robotia/BetterShops/releases

**Comment by BellemareMederic** [comment]
I can take de unoffical thx wait for official
