### ISSUE TITLE
Issue With Selling Feature. No Limit Option.

### ISSUE THREAD

**Issue by StoneLegion** [moomaxie/BetterShops#2]
Could you please consider adding a stock limit option. For example if you set to Sell mode as in players sell items to your shop it's currently unlimited. Meaning that if you wanted to buy 64 diamond blocks but they can sell you as much as they want it sort of ruins the whole feature of wanting to buy items from other players.

Thanks :)

**Comment by moomaxie** [comment]
Added in the next beta.
