### ISSUE TITLE
Bug: If you remove the shop with a full inventory you lose the items within the shop.

### ISSUE THREAD

**Issue by StoneLegion** [moomaxie/BetterShops#3]
This is a Minor bug but a pretty big one if accidents happen. If someone breaks their shop and it fills past their inventory or better yet if their inventory is already full then the items are gone for good.

Maybe do a inventory check if it's not a hard thing and just note to the user can't break shop inventory is full empty items out of shop or something around those lines.

Thanks,
Kane

**Comment by moomaxie** [comment]
Fixed in the next beta.
