### ISSUE TITLE
Complaints about shop closing when selling items

### ISSUE THREAD

**Issue by DanSpedey** [moomaxie/BetterShops#5]
Could you please change it so the shop does not close every time you try to sell an item, maybe try add a cart feature for the selling shop too?

**Comment by moomaxie** [comment]
The shop will no longer close after selling. However I don't think adding a cart feature for the selling shop is necessary at this stage, much because 1.6.0 is 99.99% done and will most likely be released this week.

**Comment by DanSpedey** [comment]
Ok thanks!
