### ISSUE TITLE
Adding a new event when the proprietary modify an item stock

### ISSUE THREAD

**Issue by Aztorius** [moomaxie/BetterShops#7]
With my plugin, I need to know all the transfers about a Shop, not only Selling and Buying events.
For example I need an event that return the shop, the item, the quantity of this item (which was transferred) and in which direction it was transferred by the proprietary of the shop.

Is this possible ?

I tried to do that without modifying Better Shops, but it's harder.

**Comment by moomaxie** [comment]
The next update will add a Transaction class that will be returned with the Buy and Sell Events. It will contain the item prices and amounts as well as other useful information.

**Comment by informaticien77** [comment]
Thanks.

**Comment by Aztorius** [comment]
But there is another problem. I would like to have a new Event that concerns the deposit or the withdrawal of an item without transaction. For example when the creator of the shop deposits an item (an amount of an item), my plugin have to be warned with a new Event.
My problem now, is that there is only two Events which concerns transactions (onBuyItem and onSellItem), but I would like to have a "onChangeStock" Event which will be more global.

**Comment by moomaxie** [comment]
I'll work on adding a bunch of new events for the next release.

**Comment by Aztorius** [comment]
Thank you.
